-- 코드를 입력하세요

WITH GET_SELLED_BOOK_ID AS (
SELECT BOOK_ID, SUM(SALES) AS "SELL_COUNT" FROM BOOK_SALES WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'GROUP BY BOOK_ID
)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(GS.SELL_COUNT * B.PRICE) AS TOTAL_SALES 
FROM BOOK B  INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID 
INNER JOIN GET_SELLED_BOOK_ID GS ON B.BOOK_ID = GS.BOOK_ID 
GROUP BY A.AUTHOR_NAME, A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;