# -- 코드를 입력하세요
# SELECT ORDER_ID, PRODUCT_ID , DATE_FORMAT(OUT_DATE,'%Y-%m-%d') AS 'OUT_DATE' , CASE WHEN OUT_DATE IS NULL THEN '출고미정'
# WHEN OUT_DATE <= '2022-05-01' THEN '출고완료'
# ELSE '출고대기' END AS '출고여부' FROM FOOD_ORDER
# ORDER BY ORDER_ID ASC;








-- 5월 1일까지는 출고완료
-- 5월 2일부터는 OUT_DATE가 출고대기
-- 널값이라면 출고미정





SELECT ORDER_ID, PRODUCT_ID, OUT_DATE, CASE 
WHEN OUT_DATE < '2022-05-02' THEN '출고완료'
WHEN OUT_DATE IS NULL THEN '출고미정'
ELSE '출고대기' END AS '출고여부'
FROM FOOD_ORDER 
ORDER BY ORDER_ID ASC;








