-- 코드를 입력하세요

-- 중복제거 안함 UNION ALL
-- DATE_FORMAT (SALES_DATE, '%Y-%m-%d')
# SELECT DATE_FORMAT (SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'

# UNION ALL

# SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, NULL,PRODUCT_ID, SALES_AMOUNT FROM OFFLINE_SALE WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01' 
# ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;


SELECT SALES_DATE,  PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01' 

UNION ALL 

SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT FROM OFFLINE_SALE WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'

ORDER BY SALES_DATE,PRODUCT_ID,USER_ID ASC;