-- 코드를 입력하세요
# SELECT C.CAR_ID, C.CAR_TYPE,
# CASE WHEN D.DURATION_TYPE = '7일 미만' THEN C.DAILY_FEE * 30
# ELSE  FLOOR(C.DAILY_FEE * 30 * (1 - (D.DISCOUNT_RATE/100))) 
# END AS FEE FROM CAR_RENTAL_COMPANY_CAR C 
# INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE ='30일 이상'
# WHERE C.CAR_TYPE IN ('세단','SUV') AND C.CAR_ID NOT IN  (
#     SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <='2022-11-30' AND
#     END_DATE >= '2022-11-01'
# ) 
# HAVING FEE >= 500000 AND FEE < 2000000
# ORDER BY FEE DESC,C.CAR_TYPE ASC, C.CAR_ID DESC;








-- 세단, SUV , 2022-11-1 ~ 2022-11-30 
-- 대여금액 50만원 이상 200만원 미만


-- 정렬기준 대여금액 내림차순, 자동차종류 오름차순, 자동차 ID 내림차순

SELECT C.CAR_ID, C.CAR_TYPE, FLOOR((C.DAILY_FEE )*  (30) * (1-P.DISCOUNT_RATE/100))  AS FEE 

FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
ON C.CAR_TYPE = P.CAR_TYPE AND  P.DURATION_TYPE ='30일 이상'

WHERE C.CAR_TYPE IN ('세단','SUV') AND NOT EXISTS (
    SELECT 1 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE H.CAR_ID = C.CAR_ID AND H.START_DATE  <= '2022-11-30' 
    AND H.END_DATE >= '2022-11-01'


)

HAVING FEE >=500000 AND FEE <2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;











