-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE,
CASE WHEN D.DURATION_TYPE = '7일 미만' THEN C.DAILY_FEE * 30
ELSE  FLOOR(C.DAILY_FEE * 30 * (1 - (D.DISCOUNT_RATE/100))) 
END AS FEE FROM CAR_RENTAL_COMPANY_CAR C 
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE ='30일 이상'
WHERE C.CAR_TYPE IN ('세단','SUV') AND C.CAR_ID NOT IN  (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <='2022-11-30' AND
    END_DATE >= '2022-11-01'
) 
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC,C.CAR_TYPE ASC, C.CAR_ID DESC;