-- 코드를 입력하세요
# SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, T.FAVORITES FROM REST_INFO R INNER JOIN (SELECT MAX(FAVORITES) AS FAVORITES, FOOD_TYPE FROM REST_INFO GROUP BY FOOD_TYPE) AS T ON T.FOOD_TYPE = R.FOOD_TYPE WHERE T.FAVORITES =R.FAVORITES ORDER BY R.FOOD_TYPE DESC;


# SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, T.FAVORITES FROM REST_INFO R
# INNER JOIN (SELECT MAX(FAVORITES) AS FAVORITES, FOOD_TYPE FROM REST_INFO GROUP BY FOOD_TYPE) AS T 
# ON R.FOOD_TYPE= T.FOOD_TYPE WHERE R.FAVORITES = T.FAVORITES ORDER BY R.FOOD_TYPE DESC;




# SELECT FOOD_TYPE, REST_ID , REST_NAME , FAVORITES FROM REST_INFO 
# WHERE (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE ) ORDER BY FOOD_TYPE DESC; 














SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES FROM REST_INFO

WHERE (FOOD_TYPE,FAVORITES) IN 
(
    SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO 
    GROUP BY FOOD_TYPE 
)

ORDER BY FOOD_TYPE DESC;





