# SELECT u.USER_ID, u.NICKNAME, CONCAT(u.CITY, ' ', u.STREET_ADDRESS1, ' ', u.STREET_ADDRESS2) AS full_address, 
#        CONCAT(SUBSTR(u.TLNO,1,3), '-', SUBSTR(u.TLNO,4,4), '-', SUBSTR(u.TLNO,8,4)) AS phone_number,
#        COUNT(*) as count 
# FROM USED_GOODS_BOARD b 
# JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID 
# GROUP BY b.WRITER_ID 
# HAVING COUNT(*) > 3;
#SELECT * FROM USED_GOODS_USER;


# SELECT u.USER_ID, u.NICKNAME, CONCAT(u.CITY,' ',u.STREET_ADDRESS1, ' ', u.STREET_ADDRESS2) AS '전체주소',
#     CONCAT(SUBSTR(u.TLNO,1,3), '-', SUBSTR(u.TLNO,4,4), '-', SUBSTR(u.TLNO,8,4)) AS '전화번호'
# FROM USED_GOODS_BOARD b JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID 
# GROUP BY b.WRITER_ID HAVING COUNT(b.WRITER_ID)>=3 ORDER BY USER_ID DESC;





-- 3건 이상 드록한 사용자ID,닉네임, 전체주소, 전화번호 조회
-- 


SELECT U.USER_ID, U.NICKNAME, CONCAT(U.CITY, ' ',U.STREET_ADDRESS1,' ', U.STREET_ADDRESS2) AS '전체주소', CONCAT (LEFT(TLNO,3), '-', SUBSTRING(TLNO,4,4) ,'-',RIGHT(TLNO,4)) AS '전화번호'
FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID 
HAVING COUNT(*) >=3 
ORDER BY U.USER_ID DESC;














