-- 코드를 입력하세요
-- Spayed Female : 중성화 됨
-- Intact 는 중성화x

# SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME FROM ANIMAL_INS I INNER JOIN ANIMAL_OUTS OUTS
# ON I.ANIMAL_ID = OUTS.ANIMAL_ID 
# WHERE ((I.SEX_UPON_INTAKE LIKE 'Intact%') AND ((OUTS.SEX_UPON_OUTCOME LIKE 'Spayed%') OR  (OUTS.SEX_UPON_OUTCOME LIKE 'Neutered%'))) 

# ORDER BY I.ANIMAL_ID ASC;












# Spayed 중성화 0
# Neutered 중성
# 들어올 당시는 중성화x, 나갈때 중성화

SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME FROM ANIMAL_INS I INNER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID 
WHERE (I.SEX_UPON_INTAKE LIKE "Intact%" ) AND ((O.SEX_UPON_OUTCOME LIKE "Spayed%") OR (O.SEX_UPON_OUTCOME LIKE "Neutered%"))
ORDER BY I.ANIMAL_ID ASC;










