-- 코드를 입력하세요

SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(REST.REVIEW_SCORE),2) AS 'SCORE' FROM REST_INFO I INNER JOIN REST_REVIEW REST ON I.REST_ID = REST.REST_ID 
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC;