-- 코드를 입력하세요
-- GENDER : 0 남자, 1: 여자
-- ONLINE_SALE : 년 , 월, 성별 별 상품구매회원수
SELECT YEAR(SALE.SALES_DATE) AS YEAR , MONTH(SALE.SALES_DATE) AS MONTH, USER.GENDER AS GENDER, COUNT(DISTINCT USER.USER_ID) AS USERS FROM  USER_INFO USER RIGHT JOIN ONLINE_SALE SALE ON USER.USER_ID = SALE.USER_ID 
WHERE GENDER IN (0,1)
GROUP BY YEAR(SALE.SALES_DATE), MONTH(SALE.SALES_DATE),USER.GENDER
ORDER BY YEAR,MONTH,GENDER;