-- 코드를 입력하세요
-- GENDER : 0 남자, 1: 여자
-- ONLINE_SALE : 년 , 월, 성별 별 상품구매회원수
# SELECT YEAR(SALE.SALES_DATE) AS YEAR , MONTH(SALE.SALES_DATE) AS MONTH, USER.GENDER AS GENDER, COUNT(DISTINCT USER.USER_ID) AS USERS FROM  USER_INFO USER RIGHT JOIN ONLINE_SALE SALE ON USER.USER_ID = SALE.USER_ID 
# WHERE GENDER IN (0,1)
# GROUP BY YEAR(SALE.SALES_DATE), MONTH(SALE.SALES_DATE),USER.GENDER
# ORDER BY YEAR,MONTH,GENDER;











# SELECT YEAR(S.SALES_DATE) AS 'YEAR', MONTH(S.SALES_DATE) AS 'MONTH', INFO.GENDER, COUNT( DISTINCT INFO.USER_ID) AS 'USERS' FROM
# USER_INFO INFO INNER JOIN ONLINE_SALE S ON INFO.USER_ID = S.USER_ID
# WHERE INFO.GENDER IS NOT NULL
# GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), INFO.GENDER
# ORDER BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), INFO.GENDER ASC;









SELECT YEAR(S.SALES_DATE) AS 'YEAR', MONTH(S.SALES_DATE) AS 'MONTH', I.GENDER, COUNT(DISTINCT I.USER_ID) AS 'USERS' FROM USER_INFO 
I INNER JOIN ONLINE_SALE S  ON I.USER_ID = S.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), I.GENDER
ORDER BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), I.GENDER ASC;















