# SELECT COUNT(*) AS "가입한 전체 회원수" FROM USER_INFO WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31';

# SELECT COUNT(*) AS "2021년에 상품구매한 회원수" 
# FROM USER_INFO U WHERE U.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
#     AND EXISTS (SELECT 1 FROM ONLINE_SALE S WHERE S.USER_ID = U.USER_ID);


WITH GET_2021 AS (
    -- 2021년에 가입한 전체 회원 ID 추출
    SELECT USER_ID 
    FROM USER_INFO 
    WHERE YEAR(JOINED) = 2021 
)
SELECT 
    YEAR(S.SALES_DATE) AS YEAR, 
    MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(*) FROM GET_2021)
    ,1) AS PURCHASED_RATIO 
FROM ONLINE_SALE S

WHERE S.USER_ID IN (
    SELECT USER_ID FROM GET_2021
) -- 2021년 가입자의 구매 내역만 필터링
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY YEAR, MONTH;