-- 코드를 입력하세요
# SELECT P.PRODUCT_ID, P.PRODUCT_NAME , (SUM(O.AMOUNT) * P.PRICE) AS TOTAL_SALES FROM FOOD_PRODUCT P
# INNER JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID 
# WHERE O.PRODUCE_DATE BETWEEN "2022-05-01" AND "2022-05-31"
# GROUP BY O.PRODUCT_ID
# ORDER BY TOTAL_SALES DESC,  P.PRODUCT_ID ASC;



-- PRODUCT_ID로 조인
-- 식품ID, 식품이름, 총매출
-- 총매출 내림차순, 식품 ID 오름차순
-- 2022년 5월 식품 

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT) * P.PRICE AS 'TOTAL_SALES' FROM FOOD_PRODUCT P
INNER JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE YEAR(O.PRODUCE_DATE) = 2022 AND MONTH(O.PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;














