-- 코드를 입력하세요
SELECT H.HISTORY_ID,
ROUND((DATEDIFF(H.END_DATE,H.START_DATE)+1) * CAR.DAILY_FEE
*(100- IFNULL(PLAN.DISCOUNT_RATE,0))/100)
AS 'FEE'
FROM CAR_RENTAL_COMPANY_CAR CAR INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON
CAR.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN ON PLAN.CAR_TYPE = CAR.CAR_TYPE
AND PLAN.DURATION_TYPE = CASE WHEN
                      DATEDIFF(H.END_DATE, H.START_DATE) +1 BETWEEN 7 AND 29 THEN '7일 이상'
                      WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 BETWEEN 30 AND 89 THEN '30일 이상'
                      WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >=90 THEN '90일 이상' 
                      ELSE NULL
                     END
WHERE CAR.CAR_TYPE ='트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;
