-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME , A.APNT_YMD FROM APPOINTMENT A INNER JOIN PATIENT P ON A.PT_NO = P.PT_NO 
INNER JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID 
WHERE A.APNT_CNCL_YN = 'N' AND (YEAR(A.APNT_YMD) = 2022 AND MONTH(A.APNT_YMD)= 4 AND DAY(A.APNT_YMD) = 13)
ORDER BY A.APNT_YMD ;