-- 코드를 입력하세요

WITH RECURSIVE hours  AS (
    
    SELECT 0 AS 'HOUR'
    UNION ALL
    SELECT HOUR +1 FROM hours WHERE HOUR <23

)
SELECT h.HOUR AS 'HOUR',COUNT(HOUR(ANI.DATETIME)) AS 'COUNT'
FROM hours h LEFT OUTER JOIN ANIMAL_OUTS ANI
ON HOUR(ANI.DATETIME) = h.HOUR
GROUP BY h.HOUR
ORDER BY h.HOUR;
