# SELECT DISTINCT
# D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
# FROM DEVELOPERS D
# INNER JOIN SKILLCODES S ON (D.SKILL_CODE & S.CODE) = S.CODE
# WHERE S.CATEGORY = 'Front End'
# ORDER BY D.ID ASC;






SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME FROM DEVELOPERS D
INNER JOIN SKILLCODES S ON (D.SKILL_CODE & S.CODE) = S.CODE
WHERE S.CATEGORY  = 'Front End'
ORDER BY D.ID ASC;























 -- 400 : 110010000
 -- 256 : 100000000
 --     : 100000000
SELECT DISTINCT DEV.ID, DEV.EMAIL, DEV.FIRST_NAME, DEV.LAST_NAME FROM SKILLCODES SKILL 
INNER JOIN DEVELOPERS DEV 
ON (SKILL.CODE & DEV.SKILL_CODE  = SKILL.CODE)
WHERE SKILL.CATEGORY ="Front End"
ORDER BY DEV.ID ASC;