-- 코드를 입력하세요
# SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS 'TOTAL_SALES' FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_USER U ON 
# B.WRITER_ID = U.USER_ID WHERE B.STATUS ='DONE' GROUP BY B.WRITER_ID HAVING SUM(B.PRICE) >=700000 ORDER BY TOTAL_SALES ASC;









-- STATUS = DONE
-- 총 금액 70만원 이상
-- 회원 ID, 닉네임, 총거래금액 조회, 
-- 총 거래금액 기준 오름차순 정렬

SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS 'TOTAL_SALES' FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_USER
U ON B.WRITER_ID = U.USER_ID 
WHERE B.STATUS = 'DONE'
GROUP BY B.WRITER_ID 
HAVING SUM(B.PRICE) >=700000
ORDER BY TOTAL_SALES ASC;



















