-- 코드를 작성해주세요
WITH BONUS_TABLE AS (
    SELECT 96 AS MIN_SCORE, 'S' AS GRADE, 0.20 AS BONUS
    UNION ALL SELECT 90,'A',0.15
    UNION ALL SELECT 80,'B', 0.10
    UNION ALL SELECT 0, 'C', 0.00
),
AVG_GRADE AS (
    SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE 
    FROM HR_GRADE
    GROUP BY EMP_NO
)
SELECT EMP.EMP_NO, EMP.EMP_NAME, BNS.GRADE AS 'GRADE', (EMP.SAL * BNS.BONUS) AS 'BONUS' 
FROM HR_EMPLOYEES EMP INNER JOIN AVG_GRADE G ON EMP.EMP_NO = G.EMP_NO
INNER JOIN BONUS_TABLE BNS ON G.AVG_SCORE>= BNS.MIN_SCORE

WHERE BNS.MIN_SCORE = (
    SELECT MAX(MIN_SCORE) FROM BONUS_TABLE
    WHERE G.AVG_SCORE >= MIN_SCORE
)

ORDER BY EMP.EMP_NO