-- 사원별 성과금 정보 조회
-- 사번, 성명, 평가 등급, 성과금을 조회하는 SQL 을 작성해라

WITH BONUS_CALC AS (
    SELECT 96 AS STANDARD_SCORE, 'S' AS  EVAL_GRADE, 0.20 AS BONUS_PER
    UNION ALL SELECT  90,'A',0.15
    UNION ALL SELECT 80, 'B', 0.10
    UNION ALL SELECT 0, 'C', 0.00
),

AVG_GRADE AS (
    SELECT EMP_NO,  AVG(SCORE) AS AVG_SCORE FROM HR_GRADE
    GROUP BY EMP_NO
)


SELECT EMP.EMP_NO , EMP.EMP_NAME, BNS.EVAL_GRADE AS 'GRADE', (BNS.BONUS_PER * EMP.SAL)  AS'BONUS' FROM HR_EMPLOYEES EMP INNER JOIN AVG_GRADE AV ON AV.EMP_NO = EMP.EMP_NO 
INNER JOIN BONUS_CALC BNS  ON AV.AVG_SCORE >=BNS.STANDARD_SCORE

WHERE BNS.STANDARD_SCORE= (
    SELECT MAX(STANDARD_SCORE) FROM BONUS_CALC 
    WHERE AV.AVG_SCORE >= STANDARD_SCORE

)

ORDER BY EMP.EMP_NO ASC;