SELECT 
    CASE
    WHEN  TO_CHAR(DATETIME,'HH24') ='09' THEN '9'
    ELSE TO_CHAR(DATETIME,'HH24') END AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS 
WHERE TO_CHAR(DATETIME,'HH24') BETWEEN 09 AND 19
GROUP BY TO_CHAR(DATETIME,'HH24')
ORDER BY TO_CHAR(DATETIME,'HH24');