-- 코드를 입력하세요
# SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE FROM MEMBER_PROFILE M INNER JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
# WHERE R.MEMBER_ID =(SELECT R.MEMBER_ID FROM REST_REVIEW R GROUP BY
#                     R.MEMBER_ID ORDER BY COUNT(*) DESC LIMIT 1
                   
#                 ) ORDER BY R.REVIEW_DATE ASC , R.REVIEW_TEXT ASC;











# SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
# FROM MEMBER_PROFILE P INNER JOIN REST_REVIEW R

# ON P.MEMBER_ID = R.MEMBER_ID

# WHERE P.MEMBER_ID = (
#     SELECT MEMBER_ID FROM  REST_REVIEW 
#     GROUP BY MEMBER_ID
#     ORDER BY COUNT(*) DESC
#     LIMIT 1)

# ORDER BY REVIEW_DATE, R.REVIEW_TEXT;






SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS 'REVIEW_DATE'
FROM MEMBER_PROFILE 
M INNER JOIN REST_REVIEW R 
ON M.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID = (
    SELECT MEMBER_ID FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC 
    LIMIT 1
)

ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;





























