SELECT CONVERT(ORIGIN.YEAR, SIGNED) AS YEAR ,(GET_MAX.MAX_SIZE-ORIGIN.SIZE_OF_COLONY) AS YEAR_DEV, ORIGIN.ID 

FROM (
    SELECT CONVERT(SUBSTRING(DIFFERENTIATION_DATE,1,4),SIGNED) AS YEAR , SIZE_OF_COLONY, ID  FROM ECOLI_DATA  
    ) ORIGIN
    
JOIN (
    SELECT CONVERT(SUBSTRING(DIFFERENTIATION_DATE,1,4),SIGNED) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)
GET_MAX

ON ORIGIN.YEAR = GET_MAX.YEAR
ORDER BY ORIGIN.YEAR, YEAR_DEV ASC;