-- 코드를 작성해주세요

SELECT COUNT(*) AS 'FISH_COUNT' 
FROM FISH_INFO ORIGIN 
INNER JOIN FISH_NAME_INFO ADDING
ON ORIGIN.FISH_TYPE = ADDING.FISH_TYPE
WHERE ADDING.FISH_NAME = 'BASS' OR ADDING.FISH_NAME = 'SNAPPER'