-- 코드를 작성해주세요

SELECT SUM(E.SCORE) AS SCORE, E.EMP_NO,P.EMP_NAME, P.POSITION , P.EMAIL FROM HR_EMPLOYEES P INNER JOIN HR_GRADE E ON P.EMP_NO = E.EMP_NO
WHERE E.YEAR = '2022'
GROUP BY E.EMP_NO ORDER BY SCORE DESC LIMIT 1;