-- 코드를 입력하세요

-- MAX 구하는 테이블 JOIN  원본 테이블 


SELECT ORIGIN.CATEGORY, ORIGIN.PRICE AS'MAX_PRICE', ORIGIN.PRODUCT_NAME 
FROM FOOD_PRODUCT ORIGIN
INNER JOIN (
    -- MAX 구하기
    SELECT CATEGORY, MAX(PRICE) AS 'CALC_MAX' FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유') 
    GROUP BY CATEGORY
) AS TEMP
ON ORIGIN.CATEGORY = TEMP.CATEGORY
AND ORIGIN.PRICE = TEMP.CALC_MAX
ORDER BY ORIGIN.PRICE DESC;