-- 코드를 입력하세요

-- MAX 구하는 테이블 JOIN  원본 테이블 


# SELECT ORIGIN.CATEGORY, ORIGIN.PRICE AS'MAX_PRICE', ORIGIN.PRODUCT_NAME 
# FROM FOOD_PRODUCT ORIGIN
# WHERE (ORIGIN.CATEGORY, ORIGIN.PRICE) IN (
#     -- MAX 구하기
#     SELECT CATEGORY, MAX(PRICE) AS 'CALC_MAX' FROM FOOD_PRODUCT
#     WHERE CATEGORY IN ('과자','국','김치','식용유') 
#     GROUP BY CATEGORY
# )
# ORDER BY ORIGIN.PRICE DESC;









SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME FROM FOOD_PRODUCT
WHERE (CATEGORY,PRICE) IN (
    SELECT CATEGORY, MAX(PRICE) FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY 
)
ORDER BY MAX_PRICE DESC;














