# SELECT COUNT(*) AS 'FISH_COUNT', MAX(LENGTH)AS 'MAX_LENGTH', FISH_TYPE FROM FISH_INFO
# GROUP BY FISH_TYPE
# HAVING AVG(IFNULL(LENGTH,10)) >=33 
# ORDER BY FISH_TYPE ASC;








-- 10CM 이하면 NULL, LENGTH가
-- 평균길이가 33 이상인 물고기들을 종류별 분류
-- 널값이라면 10으로 대체한 후 평균을 구하기 -> HAVING 조건을 사용해서

SELECT COUNT(*) AS 'FISH_COUNT', MAX(LENGTH) AS 'MAX_LENGTH', FISH_TYPE FROM FISH_INFO
GROUP BY FISH_TYPE 
HAVING AVG(IFNULL(LENGTH, 10)) >= 33
ORDER BY FISH_TYPE ASC;
