-- 코드를 작성해주세요


-- A : Front End 스킬 + Python 스킬
-- B : C# 스킬
-- C : 그 외의 FRONT END 개발자

SELECT CASE 
WHEN SUM(CASE WHEN S.NAME  = 'Python' THEN 1  ELSE  0 END) >0  AND  SUM(CASE WHEN S.CATEGORY = 'Front End' THEN 1 ELSE 0 END) >0
THEN 'A' 
WHEN SUM(CASE WHEN S.NAME = 'C#' THEN 1 ELSE 0 END) >0 THEN 'B' 
WHEN SUM(CASE WHEN S.CATEGORY ='Front End' THEN 1 ELSE 0 END) >0 THEN 'C'
END AS 'GRADE', D.ID, D.EMAIL FROM SKILLCODES S INNER JOIN DEVELOPERS D
ON (S.CODE & D.SKILL_CODE) = S.CODE
GROUP BY D.ID,D.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID ASC;
